### ISSUE TITLE
High priority: Social Media links

### ISSUE THREAD

**Issue by brocklehurstc** [atomicjam/clc#18]
Update footer to reflect new Social Media links.

Icons for twitter, facebook, instagram, linkedin

Links as follows
https://www.facebook.com/pages/Cheltenham-Ladies-College/150319208335754
https://twitter.com/cheltladiescoll
https://instagram.com/cheltladiescoll/
https://www.linkedin.com/company/the-cheltenham-ladies-college

**Comment by brocklehurstc** [comment]
High priority - don't know how I flag it as that!

**Comment by atomicjam** [comment]
set the labels on the right side of the issue to set the priority

**Comment by brocklehurstc** [comment]
Logos saved in 
W:\Marketing\ASSETS (Mktg Dept only)\Logos and Fonts\Social Media logos

**Comment by atomicjam** [comment]
added links to footer, need to tweak a few break points to make them stack correctly at smaller sizes and gif at 16px look crap, need to look at some type of vector for the logos. but its a start.
