### ISSUE TITLE
Isams Admission enquiry widget

### ISSUE THREAD

**Issue by brocklehurstc** [atomicjam/clc#21]
Tidy up styling issues.  Also think it has having an impact on the rest of the page at certain break points...

**Comment by atomicjam** [comment]
opened ticket with isams support #102240 due to issue with scope of widget

**Comment by atomicjam** [comment]
page styled and working on /isams-addmisions/ Rachel is producing copy for the top of the page and will speak with Claire in weekly meeting about the best and final place for this on the site.
